### ISSUE TITLE
Queuing new steps make animations to overshoot

### ISSUE THREAD

**Issue by lucamug** [mdgriffith/elm-animator#8]
From the Slack conversation:

I made an animation of a circle that basically goes from "left: 0px; scale(1)" to "left: 200px; scale(0)".

Every time there is a click on a page, I `Animator.queue` other steps to bring the circle in the opposite position, so I think this should not involve the "default smoothing logic".

Everything is good if I wait for the animation to end before clicking.

But if I click while the circle is transitioning to scale(0), suddenly it jumps to left > 200px.

Ellie: https://ellie-app.com/8HqJrDTrpHza1
Video: https://photos.app.goo.gl/hCr52CYJLMrJRzkr9
Surge, with debugger: http://unusual-tiger.surge.sh/test.html

From @dmy:

I think this is due to scaleX and scaleY going largely below 0 in negative values to make a smooth U-Turn (go back to 1) using the bezier interpolation.
You can log the scale values and see those:
```
16:24:10.855 scale: "scaleX(-0.3111946678161622) scaleY(-0.20746311187744143)" 5755fdf2-70f2-4982-98ab-0e3f0f575780:53:16
16:24:10.871 scale: "scaleX(-0.4066062927246094) scaleY(-0.2710708618164064)" 5755fdf2-70f2-4982-98ab-0e3f0f575780:53:16
...
```
From @mdgriffith 

Ah yeah, I think its the default smoothing logic.

From @dmy:

A better work-around than the clamp is to add the expected initial state (if the previous transition completed) with an `event (seconds 0)`  at the start of your transitions:
https://ellie-app.com/8HTKLYqX66Wa1

**Comment by mdgriffith** [comment]
Ok, just fixed a bug with queueing with this commit: https://github.com/mdgriffith/elm-animator/commit/4461b4f7274177b895a1fcf93ef1df56e403353c

I tried your example and I think it's resolved?  hard to tell for sure.

Will release a patch shortly.
